

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: rates
  backend:
    depends_on:
      - db
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://gorm:gorm@Db:5432/rates
      JWT_SECRET: 123
      JWT_SECRET_NONCE: nest
      OPEN_EXCHANGE : 
  frontend:
    depends_on:
      - backend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
       VITE_BASE_URL: http://localhost:8080